name: main

on:
  push:
    branches:
      - main
  pull_requests:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yml')}}

      - name: setup the environment
        uses: ./.github/actions/setup-python-env.yml

      - name: Run checks
        run: make checks

  tests-and-type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
      fail-fast: false

    defaults:
      run:
        shell: bash

    steps:
      - name: check out
        uses: actions/checkout@v4

      - name: setup the environment
        uses: ./.github/actions/setup-python-env.yml
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: uv run python -m pytest tests --cov --cov-config=pyproject.toml --cov-report=xml

      - name: check typing
        run: uv run mypy src
